# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
width: 520
height: 300
theme_advanced_buttons3: "removeformat,cleanup,code,pastetext,pasteword,selectall"
plugins:
 - table
 - fullscreen
 - paste
